id: P000574
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:47:47.590764
source_metadata:
  id: bdr:W22037
  title: རྟ་རྒྱུག་རྒྱལ་འཇོག
  author: ''
  volumes:
    7011dc26045c43788688af4522f81433:
      image_group_id: I1PD28028
      title: Volume 1 of rta rgyug rgyal 'jog
      volume_number: 1
      total_pages: 270
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
